---

- name: update web servers
  hosts: nodes
  become: yes
  gather_facts: false
  roles:
    - tomcat-manager-gui 
  vars: 
    req_java: java-1.8.0-openjdk.x86_64
    tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz

  tasks:
  - name: install java 
    yum:
      name: "{{req_java}}"
      state: present

  - name: downloading tomcat 
    get_url:
      url: "{{tomcat_url}}"
      dest: /usr/local

  - name: Extract downloaded tomcat file
    unarchive:
      src: "/usr/local/apache-tomcat-7.0.94.tar.gz"
      dest: /usr/local
      remote_src: yes

 # - name: renaming tomcat home
 #   command: mv /usr/local/apache-tomcat-7.0.94 /usr/local/latest

  - name: configure tomcat user xml file
    template:
      src: tomcat-users.j2
      dest: /usr/local/latest/conf/tomcat-users.xml

  - name: starting tomcat 
    shell: nohup /usr/local/latest/bin/startup.sh &

...
