---

- name: update web servers
  hosts: nodes
  become: yes


  tasks:
  - name: install git 
    package:
      name: git
      state: present

  - name: install maven
    yum: 
      name: maven
      state: latest


...
