---

- name: update web servers
  hosts: nodes
  
  vars: 
    sonar_url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.7.zip   

  tasks:
  - name: downloading sonarqube 
    get_url:
      url: "{{sonar_url}}"
      dest: /home/centos/
    become: yes

  - name: Ensure unzip software is installed before unzipping file
    package:
      name: unzip
      state: present
    become: yes
  
  - name: Extract downloaded sonarqube file
    unarchive:
      src: "/home/centos/sonarqube-6.7.7.zip"
      dest: /home/centos
      remote_src: yes
  
  - name: starting sonarqube 
    shell: nohup /home/centos/sonarqube-6.7.7/bin/linux-x86-64/sonar.sh start &

...
